### ISSUE TITLE
Trying to sort PB's by game can cause an exception

### ISSUE THREAD

**Issue by shenef** [GB127/SRC-statistics#82]
Replicated on the accounts "xdrhellx" and "nordanix", worked fine on my own account.
```
Traceback (most recent call last):
  File "C:\ASDF\Rene USB\SRC-statistics-master\main.py", line 8, in <module>
    user()
  File "C:\ASDF\Rene USB\SRC-statistics-master\user.py", line 42, in __call__
    self.__dict__[command]()
  File "C:\ASDF\Rene USB\SRC-statistics-master\generic.py", line 78, in __call__
    self.data.sort()
  File "C:\ASDF\Rene USB\SRC-statistics-master\generic.py", line 156, in __lt__
    return self.__dict__[attribut] < other.__dict__[attribut]
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

**Comment by GB127** [comment]
Because of massive change, I'll need a test on the new commit because of the new split.

**Comment by shenef** [comment]
This seems fixed as of the latest commit, could not replicate.

**Comment by GB127** [comment]
If you haven't tested yet, can you update and test? My last commit improved the code and the table display and should be better than the commit you downloaded two days ago.
